name: notebook
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  json_serializable: ^6.11.3
  build_runner: ^2.10.4


flutter:

  uses-material-design: true

